# Enumerate required environment variables for each resource type.
requiredEnv() {
  local key="${1/-/_}"
  local lookup="$key[*]"
  local pki=(
    KWM_CLUSTER_NAME
    KWM_APISERVER_PUBLIC_IP
    KWM_CONFIG_PATH_LOCAL
    KWM_ETCD_CLIENT_SANS
  )
  local cluster_admin=(
    KWM_CLUSTER_NAME
    KWM_CONFIG_PATH_LOCAL
    KWM_APISERVER_PUBLIC_IP
  )
  local cni_manifest=(
    KWM_CONFIG_PATH_REMOTE
    KWM_VERSION_KUBE_ROUTER
  )
  local controlplane_node=(
    KWM_CONNECT
    KWM_PRIVATE_IP
    KWM_HOSTNAME
    KWM_ROLE
    KWM_APISERVER_PRIVATE_IP
    KWM_CLUSTER_NAME
    KWM_VERSION_KUBERNETES
    KWM_VERSION_CNI_PLUGIN
    KWM_VERSION_CRI_CONTAINERD
    KWM_POD_CIDR
    KWM_SERVICE_CIDR
    KWM_KUBERNETES_SERVICE_IP
    KWM_DNS_SERVICE_IP
    KWM_APISERVER_PUBLIC_IP
    KWM_ETCD_SERVERS
    KWM_CONFIG_PATH_LOCAL
    KWM_CONFIG_PATH_REMOTE
  )
  local dns_manifest=(KWM_VERSION_KUBE_DNS KWM_DNS_SERVICE_IP)
  local encryption_config=(
    KWM_ENCRYPTION_KEY
  )
  local etcd_node=(
    KWM_CONNECT
    KWM_PRIVATE_IP
    KWM_HOSTNAME
    KWM_ETCD_INITIAL_CLUSTER
    KWM_VERSION_ETCD
    KWM_CONFIG_PATH_LOCAL
    KWM_CONFIG_PATH_REMOTE
  )
  local startup=(
    KWM_CLUSTER_NAME
    KWM_APISERVER_PUBLIC_IP
    KWM_APISERVER_PRIVATE_IP
    KWM_ENCRYPTION_KEY
    KWM_POD_CIDR
    KWM_SERVICE_CIDR
    KWM_KUBERNETES_SERVICE_IP
    KWM_DNS_SERVICE_IP
    KWM_CONFIG_PATH_REMOTE
    KWM_CONFIG_PATH_LOCAL
    KWM_VERSION_ETCD
    KWM_VERSION_KUBERNETES
    KWM_VERSION_KUBE_DNS
    KWM_VERSION_CNI_PLUGIN
    KWM_VERSION_CRI_CONTAINERD
    KWM_VERSION_KUBE_ROUTER
  )
  local worker_node=(
    KWM_CONNECT
    KWM_PRIVATE_IP
    KWM_HOSTNAME
    KWM_ROLE
    KWM_APISERVER_PRIVATE_IP
    KWM_CLUSTER_NAME
    KWM_VERSION_KUBERNETES
    KWM_VERSION_CNI_PLUGIN
    KWM_VERSION_CRI_CONTAINERD
    KWM_POD_CIDR
    KWM_CONFIG_PATH_LOCAL
    KWM_CONFIG_PATH_REMOTE
  )
  [[ -z "${!lookup:-}" ]] && exit 1
  printf "${!lookup}"
}
