#!/usr/bin/env bash
# Build a bundled and unbundled version of KWM.
set -euo pipefail

VERSION=${VERSION:?'needs to be defined.'}
SHA=${SHA:?'needs to be defined.'}

taskPath="$(dirname "$0")"
rootPath="$taskPath/.."
buildPath=$rootPath/build

setVersion() {
  sed "s/VERSION=dev/VERSION=\"$VERSION \/ $SHA\"/"
}

setTemplatesBundled() {
  sed "s/TEMPLATES_BUNDLED=false/TEMPLATES_BUNDLED=true/"
}

rm -rf $buildPath
mkdir -p $buildPath
$taskPath/inline-scripts < $rootPath/kwm | setVersion > $buildPath/kwm
(
  # get everything except entry point
  tac $buildPath/kwm | tail +3 | tac | setTemplatesBundled
  # compile templates
  task/compile-template $rootPath/template/**/*
  # get entry point
  tail -3 $buildPath/kwm
) > $buildPath/kwm-bundled

chmod +x $buildPath/kwm*
