#!/usr/bin/env bash
# Create a github release and tag to attach an artifact to.

here="$(dirname "$0")"
source $here/config

CHANGES=$($here/commit-history | sed 's/^/  - /' | sed 's/$/\\n/' | tr -d '\n')

data=$(cat <<EOF
{
  "tag_name": "$VERSION",
  "name": "$VERSION",
  "body": "CHANGELOG:\n$CHANGES",
  "draft": false,
  "prerelease": false
}
EOF
)

curl -X POST --data "$data" \
  -H "Accept: application/json" \
  -H "Content-Type:application/json" \
  -H "Authorization: token $GITHUB_ACCESS_TOKEN" \
  $RELEASE_ENDPOINT
