#!/usr/bin/env bash
# Delete the defined release and associated tag on github.
set -euo pipefail

here="$(dirname "$0")"
source $here/config

curl -X DELETE \
  -H "Accept: application/json" \
  -H "Authorization: token $GITHUB_ACCESS_TOKEN" \
  $RELEASE_ENDPOINT/$RELEASE_ID
