#!/usr/bin/env bash
# Update CHANGELOG with commit history.
set -euo pipefail

here="$(dirname "$0")"
VERSION=${VERSION:?'needs to be defined.'}
CHANGES="$(cat <<EOF
$VERSION:
  date: ${DATE:-$(date +%Y-%m-%d)}
  sha256: $(shasum -a 256 build/kwm | cut -d " " -f1)
  changes:
$($here/commit-history | sed 's/^/    - /')
EOF
)"

cat <<-EOF > $here/../CHANGELOG
${CHANGES}
$(cat $here/../CHANGELOG)
EOF
