#!/usr/bin/env bash
# Upload the latest built version of KWM as an artifact to the defined
# release number on github.
set -euo pipefail

here="$(dirname "$0")"
source $here/config

ARTIFACT_FILENAME=${ARTIFACT_FILENAME:?'needs to be defined.'}
ARTIFACT_FILEPATH=${ARTIFACT_FILEPATH:?'needs to be defined.'}

curl --data-binary @${ARTIFACT_FILEPATH} \
  -H "Content-Type:$(file -b --mime-type ${ARTIFACT_FILEPATH})" \
  -H "Authorization: token $GITHUB_ACCESS_TOKEN" \
  $ARTIFACT_ENDPOINT/$RELEASE_ID/assets?name=${ARTIFACT_FILENAME}
