#!/usr/bin/env bash
# Upload the latest built version of KWM as an artifact to the defined
# release number on github.

source $(dirname "$0")/config

curl --data-binary @build/kwm \
  -H "Content-Type:$(file -b --mime-type build/kwm)" \
  -H "Authorization: token $GITHUB_ACCESS_TOKEN" \
  $ARTIFACT_ENDPOINT/$RELEASE_ID/assets?name=kwm
