#!/bin/bash
set -e
OUTPUT=${OUTPUT-/dev/null}
function header { command printf "\033[0;34m$1\033[0m\n" >&3; }
function echo { command printf "$1\n" >&3; }
exec 3>&1
exec > $OUTPUT
exec 2>&1
cd "$(dirname "$0")"

${contents}
