#!/usr/bin/env bash
# Create a github release and tag to attach an artifact to.

source $(dirname "$0")/config

data=$(cat <<EOF
{
  "tag_name": "$VERSION",
  "name": "$VERSION",
  "body": "Version $VERSION",
  "draft": false,
  "prerelease": false
}
EOF
)

curl -X POST --data "$data" \
  -H "Accept: application/json" \
  -H "Content-Type:application/json" \
  -H "Authorization: token $GITHUB_ACCESS_TOKEN" \
  $RELEASE_ENDPOINT
