#!/usr/bin/env bash
# Delete the defined release and associated tag on github.

source $(dirname "$0")/config

curl -X DELETE \
  -H "Accept: application/json" \
  -H "Authorization: token $GITHUB_ACCESS_TOKEN" \
  $RELEASE_ENDPOINT/$RELEASE_ID
