#!/bin/bash

cd $(dirname "$0")
cat <<EOF
export KWM_CLUSTER_NAME=$(terraform output NAME)
export KWM_DOMAIN=test.com
export KWM_APISERVER_PUBLIC_IP=$(terraform output CONTROLPLANE_SSH_IPS | head -n 1 | sed 's/,$//')
export KWM_APISERVER_PRIVATE_IP=$(terraform output CONTROLPLANE_PRIVATE_IPS | head -n 1 | sed 's/,$//')
export KWM_POD_CIDR=10.1.0.0/16
export KWM_SERVICE_CIDR=10.10.0.0/24
export KWM_KUBERNETES_SERVICE_IP=10.10.0.1
export KWM_DNS_SERVICE_IP=10.10.0.2
export KWM_CONFIG_PATH=/etc/kubernetes
export KWM_LOCAL_PKI_PATH=pki
export KWM_VERSION_ETCD=3.2.11
export KWM_VERSION_KUBERNETES=1.9.1
export KWM_VERSION_KUBE_DNS=1.14.7
export KWM_VERSION_CNI_PLUGIN=0.6.0
export KWM_VERSION_CRI_CONTAINERD=1.0.0-beta.0
export KWM_VERSION_KUBE_ROUTER=0.0.20
EOF

function key {
  echo $1 | md5sum | cut -c1-7
}

HOSTNAMES=($(terraform output ETCD_HOSTNAMES | tr ',\n' ' '))
SSH_IPS=($(terraform output ETCD_SSH_IPS | tr ',\n' ' '))
PRIVATE_IPS=($(terraform output ETCD_PRIVATE_IPS | tr ',\n' ' '))
for idx in ${!HOSTNAMES[@]}; do
  nodeKey=$(key ${HOSTNAMES[$idx]})
  cat <<EOF
export KWM_ROLE_${nodeKey}=etcd
export KWM_HOSTNAME_${nodeKey}=${HOSTNAMES[$idx]}
export KWM_CONNECT_${nodeKey}="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@${SSH_IPS[$idx]}"
export KWM_PRIVATE_IP_${nodeKey}=${PRIVATE_IPS[$idx]}
EOF
done

HOSTNAMES=($(terraform output CONTROLPLANE_HOSTNAMES | tr ',\n' ' '))
SSH_IPS=($(terraform output CONTROLPLANE_SSH_IPS | tr ',\n' ' '))
PRIVATE_IPS=($(terraform output CONTROLPLANE_PRIVATE_IPS | tr ',\n' ' '))
for idx in ${!HOSTNAMES[@]}; do
  nodeKey=$(key ${HOSTNAMES[$idx]})
  cat <<EOF
export KWM_ROLE_${nodeKey}="controlplane worker"
export KWM_HOSTNAME_${nodeKey}=${HOSTNAMES[$idx]}
export KWM_CONNECT_${nodeKey}="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@${SSH_IPS[$idx]}"
export KWM_PRIVATE_IP_${nodeKey}=${PRIVATE_IPS[$idx]}
EOF
done

HOSTNAMES=($(terraform output WORKER_HOSTNAMES | tr ',\n' ' '))
SSH_IPS=($(terraform output WORKER_SSH_IPS | tr ',\n' ' '))
PRIVATE_IPS=($(terraform output WORKER_PRIVATE_IPS | tr ',\n' ' '))
for idx in ${!HOSTNAMES[@]}; do
  nodeKey=$(key ${HOSTNAMES[$idx]})
  cat <<EOF
export KWM_ROLE_${nodeKey}=worker
export KWM_HOSTNAME_${nodeKey}=${HOSTNAMES[$idx]}
export KWM_CONNECT_${nodeKey}="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@${SSH_IPS[$idx]}"
export KWM_PRIVATE_IP_${nodeKey}=${PRIVATE_IPS[$idx]}
EOF
done
