#!/bin/bash

here=$(dirname "$0")
(
  cd $here
  echo export KWM_CLUSTER_NAME=$(terraform output NAME)
  echo export KWM_CLUSTER_DOMAIN=test.com
  echo export KWM_POD_CIDR=10.0.0.0/16
  echo export KWM_SERVICE_CIDR=10.10.0.0/24
  echo export KWM_KUBERNETES_SERVICE_IP=10.10.0.1
  echo export KWM_DNS_SERVICE_IP=10.10.0.2
  echo export KWM_SSH_USER=root
  echo export KWM_VERSION_ETCD=3.2.11
  echo export KWM_VERSION_KUBERNETES=1.8.5
  echo export KWM_VERSION_CNI_PLUGIN=0.6.0
  echo export KWM_VERSION_KUBE_ROUTER=0.0.19
  echo export KWM_CONTROLLER_NAMES=$(terraform output CONTROLLER_NAMES | tr -d '\n')
  echo export KWM_CONTROLLER_SSH_IPS=$(terraform output CONTROLLER_SSH_IPS | tr -d '\n')
  echo export KWM_CONTROLLER_PRIVATE_IPS=$(terraform output CONTROLLER_PRIVATE_IPS | tr -d '\n')
  echo export KWM_ETCD_NAMES=$(terraform output ETCD_NAMES | tr -d '\n')
  echo export KWM_ETCD_SSH_IPS=$(terraform output ETCD_SSH_IPS | tr -d '\n')
  echo export KWM_ETCD_PRIVATE_IPS=$(terraform output ETCD_PRIVATE_IPS | tr -d '\n')
  echo export KWM_LOAD_BALANCER_SSH_IPS=$(terraform output LOAD_BALANCER_PUBLIC_IPS | tr -d '\n')
  echo export KWM_LOAD_BALANCER_PUBLIC_IPS=$(terraform output LOAD_BALANCER_PUBLIC_IPS | tr -d '\n')
  echo export KWM_NODE_NAMES=$(terraform output NODE_NAMES | tr -d '\n')
  echo export KWM_NODE_SSH_IPS=$(terraform output NODE_SSH_IPS | tr -d '\n')
  echo export KWM_NODE_PRIVATE_IPS=$(terraform output NODE_PRIVATE_IPS | tr -d '\n')
)
