#!/bin/bash

cd $(dirname "$0")
cat <<EOF
export KWM_CLUSTER_NAME=$(terraform output NAME)
export KWM_APISERVER_PUBLIC_IP=$(terraform output CONTROLPLANE_SSH_IPS | head -n 1 | sed 's/,$//')
export KWM_APISERVER_PRIVATE_IP=$(terraform output CONTROLPLANE_PRIVATE_IPS | head -n 1 | sed 's/,$//')
EOF

function key {
  echo $1 | md5sum | cut -c1-7
}

HOSTNAMES=($(terraform output ETCD_HOSTNAMES | tr ',\n' ' '))
SSH_IPS=($(terraform output ETCD_SSH_IPS | tr ',\n' ' '))
PRIVATE_IPS=($(terraform output ETCD_PRIVATE_IPS | tr ',\n' ' '))
for idx in ${!HOSTNAMES[@]}; do
  nodeKey=$(key ${HOSTNAMES[$idx]})
  cat <<EOF
export KWM_ROLE_${nodeKey}=etcd
export KWM_HOSTNAME_${nodeKey}=${HOSTNAMES[$idx]}
export KWM_CONNECT_${nodeKey}="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@${SSH_IPS[$idx]}"
export KWM_PRIVATE_IP_${nodeKey}=${PRIVATE_IPS[$idx]}
EOF
done

HOSTNAMES=($(terraform output CONTROLPLANE_HOSTNAMES | tr ',\n' ' '))
SSH_IPS=($(terraform output CONTROLPLANE_SSH_IPS | tr ',\n' ' '))
PRIVATE_IPS=($(terraform output CONTROLPLANE_PRIVATE_IPS | tr ',\n' ' '))
for idx in ${!HOSTNAMES[@]}; do
  nodeKey=$(key ${HOSTNAMES[$idx]})
  cat <<EOF
export KWM_ROLE_${nodeKey}="controlplane worker"
export KWM_HOSTNAME_${nodeKey}=${HOSTNAMES[$idx]}
export KWM_CONNECT_${nodeKey}="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@${SSH_IPS[$idx]}"
export KWM_PRIVATE_IP_${nodeKey}=${PRIVATE_IPS[$idx]}
EOF
done

HOSTNAMES=($(terraform output WORKER_HOSTNAMES | tr ',\n' ' '))
SSH_IPS=($(terraform output WORKER_SSH_IPS | tr ',\n' ' '))
PRIVATE_IPS=($(terraform output WORKER_PRIVATE_IPS | tr ',\n' ' '))
for idx in ${!HOSTNAMES[@]}; do
  nodeKey=$(key ${HOSTNAMES[$idx]})
  cat <<EOF
export KWM_ROLE_${nodeKey}=worker
export KWM_HOSTNAME_${nodeKey}=${HOSTNAMES[$idx]}
export KWM_CONNECT_${nodeKey}="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@${SSH_IPS[$idx]}"
export KWM_PRIVATE_IP_${nodeKey}=${PRIVATE_IPS[$idx]}
EOF
done
