#!/bin/bash

here=$(dirname "$0")
(
  cd $here
  echo export CLUSTER_NAME=$(terraform output NAME)
  echo export CLUSTER_DOMAIN=test.com
  echo export POD_CIDR=10.244.0.0/16
  echo export SERVICE_CIDR=10.32.0.0/24
  echo export KUBERNETES_SERVICE_IP=10.32.0.1
  echo export SSH_USER=ubuntu
  echo export CONTROLLER_NAMES=$(terraform output CONTROLLER_NAMES | tr -d '\n')
  echo export CONTROLLER_SSH_IPS=$(terraform output CONTROLLER_SSH_IPS | tr -d '\n')
  echo export CONTROLLER_PRIVATE_IPS=$(terraform output CONTROLLER_PRIVATE_IPS | tr -d '\n')
  echo export ETCD_NAMES=$(terraform output ETCD_NAMES | tr -d '\n')
  echo export ETCD_SSH_IPS=$(terraform output ETCD_SSH_IPS | tr -d '\n')
  echo export ETCD_PRIVATE_IPS=$(terraform output ETCD_PRIVATE_IPS | tr -d '\n')
  echo export LOAD_BALANCER_SSH_IPS=$(terraform output LOAD_BALANCER_PUBLIC_IPS | tr -d '\n')
  echo export LOAD_BALANCER_PUBLIC_IPS=$(terraform output LOAD_BALANCER_PUBLIC_IPS | tr -d '\n')
  echo export NODE_NAMES=$(terraform output NODE_NAMES | tr -d '\n')
  echo export NODE_SSH_IPS=$(terraform output NODE_SSH_IPS | tr -d '\n')
  echo export NODE_PRIVATE_IPS=$(terraform output NODE_PRIVATE_IPS | tr -d '\n')
)
