#!/bin/bash

cd $(dirname "$0")
cat <<EOF
export KWM_NAME=$(terraform output NAME)
export KWM_DOMAIN=test.com
export KWM_PUBLIC_IP=$(terraform output PUBLIC_IP)
export KWM_APISERVER_PRIVATE_IP=$(terraform output CONTROLPLANE_PRIVATE_IPS | head -n 1 | sed 's/,$//')
export KWM_EXEC="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@"
export KWM_POD_CIDR=10.1.0.0/16
export KWM_SERVICE_CIDR=10.10.0.0/24
export KWM_KUBERNETES_SERVICE_IP=10.10.0.1
export KWM_DNS_SERVICE_IP=10.10.0.2
export KWM_VERSION_ETCD=3.2.11
export KWM_VERSION_KUBERNETES=1.9.0
export KWM_VERSION_KUBE_DNS=1.14.7
export KWM_VERSION_CNI_PLUGIN=0.6.0
export KWM_VERSION_CRI_CONTAINERD=1.0.0-beta.0
export KWM_VERSION_KUBE_ROUTER=0.0.20
export KWM_VERSION_TRAEFIK=1.5.0-rc2
export KWM_CONTROLPLANE_NAMES=$(terraform output CONTROLPLANE_NAMES | tr -d '\n')
export KWM_CONTROLPLANE_SSH_IPS=$(terraform output CONTROLPLANE_SSH_IPS | tr -d '\n')
export KWM_CONTROLPLANE_PRIVATE_IPS=$(terraform output CONTROLPLANE_PRIVATE_IPS | tr -d '\n')
export KWM_ETCD_NAMES=$(terraform output ETCD_NAMES | tr -d '\n')
export KWM_ETCD_SSH_IPS=$(terraform output ETCD_SSH_IPS | tr -d '\n')
export KWM_ETCD_PRIVATE_IPS=$(terraform output ETCD_PRIVATE_IPS | tr -d '\n')
export KWM_WORKER_NAMES=$(terraform output WORKER_NAMES | tr -d '\n')
export KWM_WORKER_SSH_IPS=$(terraform output WORKER_SSH_IPS | tr -d '\n')
export KWM_WORKER_PRIVATE_IPS=$(terraform output WORKER_PRIVATE_IPS | tr -d '\n')
EOF
