#!/bin/bash

cd $(dirname "$0")
rm -rf cluster
mkdir -p cluster

# Parse etcd hosts into various formats for cluster service files and pki gen.
ETCD_NAMES=($(terraform output ETCD_NAMES | tr '\n,' ' '))
ETCD_SSH_IPS=($(terraform output ETCD_SSH_IPS | tr '\n,' ' '))
ETCD_PRIVATE_IPS=($(terraform output ETCD_PRIVATE_IPS | tr '\n,' ' '))
for idx in ${!ETCD_NAMES[@]}; do
  ETCD_INITIAL_CLUSTER+=",${ETCD_NAMES[$idx]}=https://${ETCD_PRIVATE_IPS[$idx]}:2380"
  ETCD_HOSTS+=",https://${ETCD_PRIVATE_IPS[$idx]}:2379"
  ETCD_CLIENT_SUBJECT_NAMES+=",IP:${ETCD_PRIVATE_IPS[$idx]},DNS:${ETCD_NAMES[$idx]}"
done
ETCD_INITIAL_CLUSTER=${ETCD_INITIAL_CLUSTER:1}
ETCD_HOSTS=${ETCD_HOSTS:1}
ETCD_CLIENT_SUBJECT_NAMES=${ETCD_CLIENT_SUBJECT_NAMES:1}

cat > cluster/pki.env <<EOF
KWM_TYPE=pki
KWM_EXEC=bash
KWM_NAME=$(terraform output NAME)
KWM_ETCD_CLIENT_SUBJECT_NAMES=${ETCD_CLIENT_SUBJECT_NAMES}
EOF

cat > cluster/root-access.env <<EOF
KWM_TYPE=root-access
KWM_EXEC=bash
KWM_NAME=$(terraform output NAME)
KWM_PUBLIC_IP=$(terraform output CONTROLPLANE_SSH_IPS | head -n 1 | sed 's/,$//')
EOF

cat > cluster/manifests.env <<EOF
KWM_TYPE=manifests
KWM_EXEC=bash
KWM_VERSION_KUBE_ROUTER=0.0.20
KWM_VERSION_KUBE_DNS=1.14.7
KWM_VERSION_TRAEFIK=1.5.0-rc2
KWM_DNS_SERVICE_IP=10.10.0.2
EOF

for idx in ${!ETCD_NAMES[@]}; do
  cat > cluster/${ETCD_NAMES[$idx]}.env <<EOF
KWM_TYPE=etcd
KWM_EXEC="ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@${ETCD_SSH_IPS[$idx]}"
KWM_SSH_IP=${ETCD_SSH_IPS[$idx]}
KWM_PRIVATE_IP=${ETCD_PRIVATE_IPS[$idx]}
KWM_HOSTNAME=${ETCD_NAMES[$idx]}
KWM_ETCD_INITIAL_CLUSTER="${ETCD_INITIAL_CLUSTER}"
KWM_VERSION_ETCD=3.2.11
EOF
done

CONTROLPLANE_NAMES=($(terraform output CONTROLPLANE_NAMES | tr '\n,' ' '))
CONTROLPLANE_SSH_IPS=($(terraform output CONTROLPLANE_SSH_IPS | tr '\n,' ' '))
CONTROLPLANE_PRIVATE_IPS=($(terraform output CONTROLPLANE_PRIVATE_IPS | tr '\n,' ' '))
for idx in ${!CONTROLPLANE_NAMES[@]}; do
  cat > cluster/${CONTROLPLANE_NAMES[$idx]}.env <<EOF
KWM_TYPE=controlplane
KWM_ROLE=controlplane
KWM_EXEC="ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@${CONTROLPLANE_SSH_IPS[$idx]}"
KWM_SSH_IP=${CONTROLPLANE_SSH_IPS[$idx]}
KWM_PRIVATE_IP=${CONTROLPLANE_PRIVATE_IPS[$idx]}
KWM_APISERVER_PRIVATE_IP=$(terraform output CONTROLPLANE_PRIVATE_IPS | head -n 1 | sed 's/,$//')
KWM_HOSTNAME=${CONTROLPLANE_NAMES[$idx]}
KWM_NAME=$(terraform output NAME)
KWM_VERSION_KUBERNETES=1.9.0
KWM_VERSION_CNI_PLUGIN=0.6.0
KWM_VERSION_CRI_CONTAINERD=1.0.0-beta.0
KWM_POD_CIDR=10.1.0.0/16
KWM_SERVICE_CIDR=10.10.0.0/24
KWM_KUBERNETES_SERVICE_IP=10.10.0.1
KWM_DNS_SERVICE_IP=10.10.0.2
KWM_PUBLIC_IP=$(terraform output CONTROLPLANE_SSH_IPS | head -n 1 | sed 's/,$//')
KWM_ETCD_HOSTS="${ETCD_HOSTS}"
EOF
done

WORKER_NAMES=($(terraform output WORKER_NAMES | tr '\n,' ' '))
WORKER_SSH_IPS=($(terraform output WORKER_SSH_IPS | tr '\n,' ' '))
WORKER_PRIVATE_IPS=($(terraform output WORKER_PRIVATE_IPS | tr '\n,' ' '))
for idx in ${!WORKER_NAMES[@]}; do
  cat > cluster/${WORKER_NAMES[$idx]}.env <<EOF
KWM_TYPE=worker
KWM_ROLE=worker
KWM_EXEC="ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@${WORKER_SSH_IPS[$idx]}"
KWM_SSH_IP=${WORKER_SSH_IPS[$idx]}
KWM_PRIVATE_IP=${WORKER_PRIVATE_IPS[$idx]}
KWM_APISERVER_PRIVATE_IP=$(terraform output CONTROLPLANE_PRIVATE_IPS | head -n 1 | sed 's/,$//')
KWM_HOSTNAME=${WORKER_NAMES[$idx]}
KWM_NAME=$(terraform output NAME)
KWM_VERSION_KUBERNETES=1.9.0
KWM_VERSION_CNI_PLUGIN=0.6.0
KWM_VERSION_CRI_CONTAINERD=1.0.0-beta.0
KWM_POD_CIDR=10.1.0.0/16
EOF
done
