#!/usr/bin/env bash

source $(dirname "$0")/config

main() {
  local templatesStartAt="$(getLineOf "#--EMBED-TEMPLATES-HERE--#" "$(<kwm)")"
  mkdir -p build
  cat kwm | sed "s/VERSION=dev/VERSION=$VERSION/" > build/kwm
  cat <<EOF | ed -s build/kwm
${templatesStartAt}a
$(compileTemplates)
.
-1,.j
wq
EOF
  chmod +x build/kwm
}

getLineOf() {
  grep -n "$1" <<<"$2" | cut -d: -f 1
}

allUnderscores() {
  sed 's/[\/-]/_/g'
}

# Ensures templates with backslash line continuations retain their
# newlines through heredoc template expansion.
escapeBackslashes() {
  sed 's:\\:\\\\\\:g'
}

heredocWrapper() {
  echo "\$(cat <<'TEMPLATE'"
  echo -e "$1"
  echo "TEMPLATE"
  echo ")"
}

compileTemplates() {
  local key content
  find template -type file | while read item; do
    key="$(allUnderscores <<<$item)"
    content="$(heredocWrapper "$(escapeBackslashes <<<"$(cat $item)")")"
    echo -e "export $key=$content\n"
  done
}

main "@"
