#!/usr/bin/env bash

GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN:?'needs to be defined.'}
REPO=$(sed 's/.*:\(.*\).git/\1/' <<<"$(git config --get remote.origin.url)")
RELEASE_ENDPOINT=https://api.github.com/repos/$REPO/releases
ARTIFACT_ENDPOINT=https://uploads.github.com/repos/$REPO/releases
VERSION=${VERSION:?'please specify'}
RELEASE_ID=$(
  curl -sS \
    -H "Authorization: token $GITHUB_ACCESS_TOKEN" \
    $RELEASE_ENDPOINT/tags/$VERSION | jq '.id'
)
