#!/usr/bin/env bash

source $(dirname "$0")/config

curl --data-binary @kwm.tar.gz \
  -H "Content-Type:$(file -b --mime-type kwm.tar.gz)" \
  -H "Authorization: token $GITHUB_ACCESS_TOKEN" \
  $ARTIFACT_ENDPOINT/$RELEASE_ID/assets?name=kwm-$VERSION.tar.gz
