#!/bin/bash
set -e
OUTPUT=${OUTPUT-/dev/null}
BLUE='\033[0;34m'
NO_COLOR='\033[0m'
function log {
  message=$1
  indent=$2
  command printf "\n$(printf "%${indent}s\n")${BLUE}${message}${NO_COLOR}" >&3
}
exec 3>&1
exec > $OUTPUT
exec 2>&1
